apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: <your-new-image-name> # Make sure to use the image you built with the updated app.py
        name: vote
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 80
          name: vote
        # --- ADD THIS SECTION ---
        env:
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: STATSD_PORT
          value: "8125"
        # --- END OF ADDED SECTION ---
