name: Build, Scan, Push & Deploy (vote)

on:
  workflow_dispatch:
  push:
    branches: ["Add-StatsD"]

env:
  PROJECT_ID: sysdig-setup
  REGION: us-central1
  REPO: voting-app
  IMAGE_NAME: vote
  CLUSTER: sysdig-gke-standard
  CLUSTER_LOCATION: us-central1
  NAMESPACE: voting
  DEPLOYMENT: vote
  IMAGE_TAG: StatsD

  # Sysdig
  SYSDIG_API_URL: ${{ secrets.SYSDIG_API_URL }}
  SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to GCP
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # Build Image
      - name: Build image
        run: |
          IMAGE_URI=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI ./vote

      # Sysdig Scan (non-blocking)
      - name: Install Sysdig CLI Scanner
        run: |
          VERSION=$(curl -fsSL https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)
          curl -fsSL -o sysdig-cli-scanner \
            https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/${VERSION}/linux/amd64/sysdig-cli-scanner
          chmod +x sysdig-cli-scanner

      - name: Scan image (do not fail)
        continue-on-error: true
        run: |
          ./sysdig-cli-scanner --apiurl "$SYSDIG_API_URL" "$IMAGE_URI"

      # Push to Artifact Registry
      - name: Push image
        run: |
          docker push $IMAGE_URI

      # Deploy to GKE
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          # Use ${{ env.VAR }} here because this is an 'Action' input
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.CLUSTER_LOCATION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Update deployment image
        # Use standard $VAR here because this is a 'Shell' script
        run: |
          kubectl -n $NAMESPACE set image deployment/$DEPLOYMENT \
            $DEPLOYMENT=$IMAGE_URI

          kubectl -n $NAMESPACE rollout status deployment/$DEPLOYMENT
