name: Build & Scan (vote, worker, result) - Sysdig CLI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        svc:
          - name: vote
            path: ./vote
          - name: worker
            path: ./worker
          - name: result
            path: ./result

    env:
      IMAGE_TAG: latest
      SYSDIG_API_URL: ${{ secrets.SYSDIG_API_URL }}
      SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: |
          IMAGE_NAME="voting-${{ matrix.svc.name }}:${IMAGE_TAG}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t "$IMAGE_NAME" "${{ matrix.svc.path }}"

      - name: Install Sysdig CLI Scanner
        run: |
          VERSION=$(curl -fsSL https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)
          curl -fsSL -o sysdig-cli-scanner \
            https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/${VERSION}/linux/amd64/sysdig-cli-scanner
          chmod +x sysdig-cli-scanner

      - name: Scan image with Sysdig CLI
        run: |
          ./sysdig-cli-scanner --apiurl "$SYSDIG_API_URL" "$IMAGE_NAME"
