name: Build Push Deploy

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: sysdig-setup
  REGION: us-central1
  REPO: voting-app
  IMAGE: vote
  CLUSTER: sysdig-gke-standard
  CLUSTER_LOCATION: us-central1
  NAMESPACE: voting
  DEPLOYMENT: vote

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build + Push
        run: |
          TAG=${{ github.sha }}
          IMAGE_URI=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.CLUSTER_LOCATION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy (update image)
        run: |
          kubectl -n $NAMESPACE set image deployment/$DEPLOYMENT $DEPLOYMENT=$IMAGE_URI
          kubectl -n $NAMESPACE rollout status deployment/$DEPLOYMENT
